#
# This file is part of LUNA.
#
# Copyright (c) 2023 Great Scott Gadgets <info@greatscottgadgets.com>
# SPDX-License-Identifier: BSD-3-Clause

"""Generate Rust support files for SoC designs."""

from .introspect import Introspect

from lambdasoc.soc.cpu import CPUSoC

import datetime
import logging

class GenRust:
    def __init__(self, soc: CPUSoC):
        self._soc = soc

    # - memory.x generation ---------------------------------------------------
    def generate_memory_x(self, file=None):
        """ Generate a memory.x file for the given SoC"""

        def emit(content):
            """ Utility function that emits a string to the targeted file. """
            print(content, file=file)

        # warning header
        emit("/*")
        emit(" * Automatically generated by LUNA; edits will be discarded on rebuild.")
        emit(" * (Most header files phrase this 'Do not edit.'; be warned accordingly.)")
        emit(" *")
        emit(f" * Generated: {datetime.datetime.now()}.")
        emit(" */")
        emit("")

        # memory regions
        emit("MEMORY {")
        for window, (start, stop, ratio) in self._soc.memory_map.windows():
            if window.name not in ["bootrom", "scratchpad", "internal_sram"]:
                logging.info("Skipping non-memory resource: {}".format(window.name))
                continue
            emit(f"    {window.name} : ORIGIN = 0x{start:08x}, LENGTH = 0x{stop-start:08x}")
        emit("}")
        emit("")

        # region aliases
        aliases = {
            "REGION_TEXT":   "internal_sram",
            "REGION_RODATA": "internal_sram",
            "REGION_DATA":   "internal_sram",
            "REGION_BSS":    "internal_sram",
            "REGION_HEAP":   "internal_sram",
            "REGION_STACK":  "internal_sram",
        }
        for alias, region in aliases.items():
            emit(f"REGION_ALIAS(\"{alias}\", {region});")
